"""Stable error codes returned through ExecuteTask.action."""

SUCCESS = 0
INVALID_TASK_ID = 1
INVALID_TARGET_CLASS = 2
MOVE_BASE_UNAVAILABLE = 3
LOCALIZATION_NOT_READY = 4
GOAL_UNAVAILABLE = 5
NAVIGATION_TIMEOUT = 6
NAVIGATION_ABORTED = 7
TASK_PREEMPTED = 8
PERCEPTION_UNAVAILABLE = 9
OBJECT_NOT_FOUND = 10
ALIGNMENT_FAILED = 11
MANIPULATION_FAILED = 12
GRASP_FAILED = 13
INTERNAL_ERROR = 255
