"""Stable error codes returned through ExecuteTask.action."""

SUCCESS = 0
INVALID_TASK_ID = 1
INVALID_TARGET_CLASS = 2
MOVE_BASE_UNAVAILABLE = 3
LOCALIZATION_NOT_READY = 4
GOAL_UNAVAILABLE = 5
NAVIGATION_TIMEOUT = 6
NAVIGATION_ABORTED = 7
TASK_PREEMPTED = 8
INTERNAL_ERROR = 255
