"""Mission stage constants shared by the current navigation milestone."""

IDLE = 0
ACCEPT_TASK = 1
VALIDATE_TASK = 2
CHECK_LOCALIZATION = 3
GET_PICKUP_STAGING_GOAL = 4
NAVIGATE_TO_PICKUP_STAGING = 5
ARRIVED_PICKUP_STAGING = 6
OBSERVE_PICKUP_CANDIDATE = 7
NAVIGATE_TO_PICKUP_CANDIDATE = 8
LOCALIZE_TARGET = 9
ALIGN_FOR_GRASP = 10
OPEN_GRIPPER = 11
GRASP_OBJECT = 12
VERIFY_GRASP = 13
OBJECT_GRASPED = 14
GET_DELIVERY_GOAL = 15
NAVIGATE_TO_DELIVERY = 16
ARRIVED_DELIVERY = 17
RELEASE_OBJECT = 18
TASK_COMPLETED = 20
TASK_FAILED = 250

""" NAME字典将数字转化与字符串 """
NAMES = {
    IDLE: "IDLE",
    ACCEPT_TASK: "ACCEPT_TASK",
    VALIDATE_TASK: "VALIDATE_TASK",
    CHECK_LOCALIZATION: "CHECK_LOCALIZATION",
    GET_PICKUP_STAGING_GOAL: "GET_PICKUP_STAGING_GOAL",
    NAVIGATE_TO_PICKUP_STAGING: "NAVIGATE_TO_PICKUP_STAGING",
    ARRIVED_PICKUP_STAGING: "ARRIVED_PICKUP_STAGING",
    OBSERVE_PICKUP_CANDIDATE: "OBSERVE_PICKUP_CANDIDATE",
    NAVIGATE_TO_PICKUP_CANDIDATE: "NAVIGATE_TO_PICKUP_CANDIDATE",
    LOCALIZE_TARGET: "LOCALIZE_TARGET",
    ALIGN_FOR_GRASP: "ALIGN_FOR_GRASP",
    OPEN_GRIPPER: "OPEN_GRIPPER",
    GRASP_OBJECT: "GRASP_OBJECT",
    VERIFY_GRASP: "VERIFY_GRASP",
    OBJECT_GRASPED: "OBJECT_GRASPED",
    GET_DELIVERY_GOAL: "GET_DELIVERY_GOAL",
    NAVIGATE_TO_DELIVERY: "NAVIGATE_TO_DELIVERY",
    ARRIVED_DELIVERY: "ARRIVED_DELIVERY",
    RELEASE_OBJECT: "RELEASE_OBJECT",
    TASK_COMPLETED: "TASK_COMPLETED",
    TASK_FAILED: "TASK_FAILED",
}
