"""Mission stage constants shared by the current navigation milestone."""

IDLE = 0
ACCEPT_TASK = 1
VALIDATE_TASK = 2
CHECK_LOCALIZATION = 3
GET_PICKUP_STAGING_GOAL = 4
NAVIGATE_TO_PICKUP_STAGING = 5
ARRIVED_PICKUP_STAGING = 6
TASK_FAILED = 250

NAMES = {
    IDLE: "IDLE",
    ACCEPT_TASK: "ACCEPT_TASK",
    VALIDATE_TASK: "VALIDATE_TASK",
    CHECK_LOCALIZATION: "CHECK_LOCALIZATION",
    GET_PICKUP_STAGING_GOAL: "GET_PICKUP_STAGING_GOAL",
    NAVIGATE_TO_PICKUP_STAGING: "NAVIGATE_TO_PICKUP_STAGING",
    ARRIVED_PICKUP_STAGING: "ARRIVED_PICKUP_STAGING",
    TASK_FAILED: "TASK_FAILED",
}
