<?xml version="1.0"?>
<package format="2">
  <name>smart_factory_bringup</name>
  <version>0.1.0</version>
  <description>Launch orchestration for the smart factory simulation.</description>

  <maintainer email="ianichinose@todo.todo">ianichinose</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>gazebo_nav</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>smart_factory_mission</exec_depend>
</package>
